### ISSUE TITLE
AZDO_ACCOUNT replaced by AZDO_URL

### ISSUE THREAD

**Issue by ugumba** [codez-one/docker-azure-pipelines-agent#2]
Just a heads up for anyone else trying it out:
Replace "-e AZDO_ACCOUNT=blah" with "-e AZDO_URL=https://blah.visualstudio.com".

Thanks!

**Comment by kirkone** [comment]
Hi. Good catch. I have to update the readme. 
Thanks for letting me know.

**Comment by hangy** [comment]
I think this was closed in 938a5030dcf2422a65201c5788e3d469db2ee06e.

**Comment by kirkone** [comment]
Jepp, missed that, thanks!
